name: Validate Merge Request Source Branch
on:
  pull_request:
    branches:
      - master
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch
        run: |
          if [ ${{ github.head_ref }} != "development" ] && [ ${{ github.base_ref }} == "master" ]; then
            echo "Merge requests to master are only allowed from development branch"
            exit 1
          fi
